### ISSUE TITLE
Target Gear During Shift not set correctly

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/transmission-control-module#10]
Looking at the data, it looks like the target gear while shifting is the gear that is being left, not the gear that the car is trying to enter. Investigate and fix an issue if needed.

![image](https://user-images.githubusercontent.com/52789184/195902456-cc6d26ac-8af8-4004-b92b-696a6d6e5783.png)

**Comment by AlexT2052** [comment]
Fixed in Calvin's repository overhaul
